version: '2'

services:
    web:
        image: astondevops/docker-web-flask
        container_name: web_flask
        ports:
            - "5000:5000"
        command: ["-h=0.0.0.0"]
    jmeter:
        image : astondevops/docker-jmeter
        container_name: jmeter_web_flask
        volumes:
            - ./results:/results
        command: ["-H", "web", "-P", "5000"]
        links:
            - web
